import { BadgeVariant, NonProgrammaticBadges } from './types';
import { Season } from '../../../hooks/season/types';

export const BADGE_TYPE_BADGE_VARIANT_MAP: Record<string, BadgeVariant> = {
  // season 1
  '16': 'fixedTrader',
  '17': 'deltaDegen',
  '18': 'leverageCrowbar',
  '19': 'irsConnoisseur',
  '20': 'sushiRoll',
  '21': 'degenStuff',
  '22': 'okBoomer',
  '23': 'lpoor',
  '24': 'moneyMoneyMoney',
  '25': 'waterHose',
  '26': 'rainMaker',
  '27': 'dryIce',
  '28': 'beWaterMyFriend',
  '29': 'yikes',
  '30': 'maxBidding',
  '31': 'topTrader',
  '32': 'mellowLpVault',
  // season OG
  '0': 'ogFixedTrader',
  '1': 'ogDeltaDegen',
  '2': 'ogLeverageCrowbar',
  '3': 'ogIrsConnoisseur',
  '4': 'ogSushiRoll',
  '5': 'ogDegenStuff',
  '6': 'ogOkBoomer',
  '7': 'ogLpoor',
  '8': 'ogMoneyMoneyMoney',
  '9': 'ogWaterHose',
  '10': 'ogRainMaker',
  '11': 'ogDryIce',
  '12': 'ogBeWaterMyFriend',
  '13': 'ogYikes',
  '14': 'ogMaxBidding',
  '15': 'ogTopTrader',
  // non-programmatic badges
  '34': 'governorz',
  '33': 'diplomatz',
  '35': 'senatorz',
};

export const NON_PROGRAMMATIC_BADGES: NonProgrammaticBadges[] = [
  'governorz',
  'diplomatz',
  'senatorz',
  'whaleWhisperer',
  'notionalInfluencer',
  'referror',
];

export const SEASON_BADGE_VARIANTS: Record<`${Season['id']}`, string[]> = {
  0: [
    'ogFixedTrader',
    'ogDeltaDegen',
    'ogLeverageCrowbar',
    'ogIrsConnoisseur',
    'ogSushiRoll',
    'ogDegenStuff',
    'ogTopTrader',
    'ogOkBoomer',
    'ogDryIce',
    'ogMaxBidding',
    'ogYikes',
    'ogLpoor',
    'ogMoneyMoneyMoney',
    'ogWaterHose',
    'ogRainMaker',
    'ogBeWaterMyFriend',
    ...NON_PROGRAMMATIC_BADGES,
  ],
  1: [
    'fixedTrader',
    'deltaDegen',
    'leverageCrowbar',
    'irsConnoisseur',
    'sushiRoll',
    'degenStuff',
    'topTrader',
    'okBoomer',
    'dryIce',
    'maxBidding',
    'yikes',
    'lpoor',
    'mellowLpVault',
    'moneyMoneyMoney',
    'waterHose',
    'rainMaker',
    'beWaterMyFriend',
    ...NON_PROGRAMMATIC_BADGES,
  ],
  2: [],
  3: [],
  4: [],
  5: [],
};
