export const routes = {
  POOLS: 'pools',
  PORTFOLIO_POSITIONS: 'portfolio/positions',
  PORTFOLIO_OPTIMISERS: 'portfolio/optimisers',
  PORTFOLIO_OVERVIEW: 'portfolio/overview',
  PORTFOLIO_MARGIN_ACCOUNTS: 'portfolio/margin-accounts',
  TRADING_LEAGUE: 'trading-league',
  PROFILE: 'profile',
  VOYAGE: 'voyage',
  LP_OPTIMISERS: 'lp-optimisers',
  LP_OPTIMISERS_DEPOSIT_FORM: 'lp-optimisers/:actions/:vaultId',
  LP_OPTIMISERS_WITHDRAW_ROLLOVER_FORM: 'lp-optimisers/:actions/:vaultId/:vaultIndex',
  TRADER_SWAP_FORM: 'trader/swap/:ammId/:poolId',
  TRADER_ROLLOVER_SWAP_FORM: 'trader/rollover/:ammId/:positionId/:poolId',
  LP_FORM: 'lp/liquidity/:ammId/:poolId?',
  LP_ROLLOVER_FORM: 'lp/rollover/:ammId/:positionId/:poolId',
};
