export enum SwapFormActions {
  UPDATE='UPDATE',
  SWAP='SWAP',
  FCM_SWAP='FCM_SWAP',
  FCM_UNWIND='FCM_UNWIND',
  ROLLOVER_FCM_SWAP='ROLLOVER_FCM_SWAP',
  ROLLOVER_SWAP='ROLLOVER_SWAP'
};

export enum SwapFormModes {
  FIX_BORROW='FIX_BORROW',
  NEW_POSITION='NEW_POSITION',
  EDIT_MARGIN='EDIT_MARGIN',
  ROLLOVER='ROLLOVER',
};