import { SupportedChainId } from '@voltz-protocol/v1-sdk';

export const mockGetMarginAccountsPage1 = {
  marginAccounts: [
    {
      id: '1',
      chainId: SupportedChainId.mainnet,
      name: 'A Wild Broccoli 🥦',
      balance: 123456,
      positionsCount: 1,
      marginRatioPercentage: 15,
      marginRatioHealth: 'healthy',
    },
    {
      id: '2',
      chainId: SupportedChainId.avalanche,
      name: 'Moonwalking Astronaut 🚀',
      balance: 98765,
      positionsCount: 2,
      marginRatioPercentage: 30,
      marginRatioHealth: 'healthy',
    },
    {
      id: '3',
      chainId: SupportedChainId.arbitrum,
      name: 'Disco Panda 🐼🕺',
      balance: 65432,
      positionsCount: 3,
      marginRatioPercentage: 45,
      marginRatioHealth: 'warning',
    },
    {
      id: '4',
      chainId: SupportedChainId.avalanche,
      name: 'Pizza Lover 🍕❤️',
      balance: 54321,
      positionsCount: 4,
      marginRatioPercentage: 60,
      marginRatioHealth: 'warning',
    },
    {
      id: '5',
      chainId: SupportedChainId.avalanche,
      name: 'Crypto Surfer 🏄‍♂️',
      balance: 87654,
      positionsCount: 5,
      marginRatioPercentage: 75,
      marginRatioHealth: 'warning',
    },
    {
      id: '6',
      chainId: SupportedChainId.mainnet,
      name: 'Captain Doughnut 🍩⚓️',
      balance: 23456,
      positionsCount: 6,
      marginRatioPercentage: 90,
      marginRatioHealth: 'danger',
    },
    {
      id: '7',
      chainId: SupportedChainId.arbitrum,
      name: 'Zombie Unicorn 🦄🧟',
      balance: 34567,
      positionsCount: 7,
      marginRatioPercentage: 20,
      marginRatioHealth: 'healthy',
    },
    {
      id: '8',
      chainId: SupportedChainId.arbitrum,
      name: 'Fluffy Cactus 🌵🌈',
      balance: 45678,
      positionsCount: 8,
      marginRatioPercentage: 35,
      marginRatioHealth: 'healthy',
    },
    {
      id: '9',
      chainId: SupportedChainId.goerli,
      name: 'Robot DJ 🤖🎧',
      balance: 56789,
      positionsCount: 9,
      marginRatioPercentage: 50,
      marginRatioHealth: 'warning',
    },
    {
      id: '10',
      chainId: SupportedChainId.mainnet,
      name: 'Pancake Master 🥞👑',
      balance: 78901,
      positionsCount: 10,
      marginRatioPercentage: 65,
      marginRatioHealth: 'warning',
    },
  ],
  totalMarginAccounts: 15,
};

export const mockGetMarginAccountsPage2 = {
  marginAccounts: [
    {
      id: '11',
      chainId: SupportedChainId.goerli,
      name: 'Ninja Turtle 🐢🥷',
      balance: 34567,
      positionsCount: 11,
      marginRatioPercentage: 80,
      marginRatioHealth: 'warning',
    },
    {
      id: '12',
      chainId: SupportedChainId.mainnet,
      name: 'Mermaid Diva 🧜‍♀️🎤',
      balance: 23456,
      positionsCount: 12,
      marginRatioPercentage: 10,
      marginRatioHealth: 'healthy',
    },
    {
      id: '13',
      chainId: SupportedChainId.mainnet,
      name: 'Sushi Addict 🍣🍱',
      balance: 87654,
      positionsCount: 13,
      marginRatioPercentage: 25,
      marginRatioHealth: 'healthy',
    },
    {
      id: '14',
      chainId: SupportedChainId.mainnet,
      name: 'Pixel Wizard 🧙‍♂️🎮',
      balance: 76543,
      positionsCount: 14,
      marginRatioPercentage: 40,
      marginRatioHealth: 'healthy',
    },
    {
      id: '15',
      chainId: SupportedChainId.mainnet,
      name: 'Space Penguin 🐧🪐',
      balance: 65432,
      positionsCount: 15,
      marginRatioPercentage: 55,
      marginRatioHealth: 'warning',
    },
  ],
  totalMarginAccounts: 15,
};
