import { Position } from '@voltz-protocol/v1-sdk';

export const positionsMock: Pick<
  Position,
  | 'notionalInUSD'
  | 'marginInUSD'
  | 'accruedCashflowInUSD'
  | 'receivingRate'
  | 'variableTokenBalance'
  | 'payingRate'
  | 'healthFactor'
>[] = [
  {
    notionalInUSD: 10,
    marginInUSD: 10,
    accruedCashflowInUSD: 0.005009492899397767,
    receivingRate: 1.2949495175313324,
    variableTokenBalance: -10,
    payingRate: 0.0002510293848567713,
    healthFactor: 3,
  },
  {
    notionalInUSD: 4004.950211860179,
    marginInUSD: 633.635,
    accruedCashflowInUSD: 33.26138431138622,
    receivingRate: 25.614581851142958,
    variableTokenBalance: 3.160297499238662,
    payingRate: 1.6224979948751188,
    healthFactor: 3,
  },
  {
    notionalInUSD: 126.727,
    marginInUSD: 126.727,
    accruedCashflowInUSD: 0.9683690575836278,
    receivingRate: 0,
    variableTokenBalance: 0.1,
    payingRate: 0,
    healthFactor: 2,
  },
  {
    notionalInUSD: 633.635,
    marginInUSD: 12.6727,
    accruedCashflowInUSD: -4.638119276879107,
    receivingRate: 0,
    variableTokenBalance: -0.5,
    payingRate: 0,
    healthFactor: 1,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 1,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
  {
    notionalInUSD: 0,
    marginInUSD: 0,
    accruedCashflowInUSD: 0,
    receivingRate: 0,
    variableTokenBalance: 0,
    payingRate: 0,
    healthFactor: 0,
  },
];
