import { SupportedChainId } from '@voltz-protocol/v1-sdk';

import { PositionMock } from './index';

export const positionMocks: PositionMock[] = [
  {
    type: 'LP',
    id: '1',
    chainId: SupportedChainId.mainnet,
    market: 'Aave',
    token: 'eth',
    name: 'Position 1',
    notional: 1000,
    margin: 200,
    termEndTimestampInMS: 1654022400000,
    status: {
      variant: 'none',
      value: 0,
    },
    unrealizedPNL: 0,
    realizedPNL: 0,
    isBorrowing: false,
    isAaveV3: true,
    isV2: false,
  },
  {
    type: 'Variable',
    id: '2',
    chainId: SupportedChainId.mainnet,
    market: 'Compound',
    token: 'usdc',
    name: 'Position 2',
    notional: 500,
    margin: 100,
    termEndTimestampInMS: 1654022400000,
    status: {
      variant: 'in-range',
      value: 50,
    },
    unrealizedPNL: 10,
    realizedPNL: 20,
    isBorrowing: true,
    isAaveV3: false,
    isV2: true,
  },
  {
    type: 'Fixed',
    id: '3',
    chainId: SupportedChainId.avalanche,
    market: 'Lido',
    token: 'eth',
    name: 'Position 3',
    notional: 1500,
    margin: 300,
    termEndTimestampInMS: 1654022400000,
    status: {
      variant: 'paying',
      value: 75,
    },
    unrealizedPNL: -5,
    realizedPNL: -10,
    isBorrowing: false,
    isAaveV3: true,
    isV2: true,
  },
  {
    type: 'Variable',
    id: '4',
    chainId: SupportedChainId.avalanche,
    market: 'Rocket',
    token: 'dai',
    name: 'Position 4',
    notional: 2000,
    margin: 400,
    termEndTimestampInMS: 1654022400000,
    status: {
      variant: 'receiving',
      value: 25,
    },
    unrealizedPNL: 15,
    realizedPNL: 30,
    isBorrowing: true,
    isAaveV3: false,
    isV2: false,
  },
  {
    type: 'Fixed',
    id: '5',
    chainId: SupportedChainId.arbitrum,
    market: 'GMX:GLP',
    token: 'eth',
    name: 'Position 5',
    notional: 2500,
    margin: 500,
    termEndTimestampInMS: 1654022400000,
    status: {
      variant: 'in-range',
      value: 60,
    },
    unrealizedPNL: 20,
    realizedPNL: 40,
    isBorrowing: true,
    isAaveV3: true,
    isV2: false,
  },
  {
    type: 'LP',
    id: '6',
    chainId: SupportedChainId.arbitrum,
    market: 'SOFR',
    token: 'usdt',
    name: 'Position 6',
    notional: 3000,
    margin: 600,
    termEndTimestampInMS: 1654022400000,
    status: {
      variant: 'none',
      value: 0,
    },
    unrealizedPNL: 5,
    realizedPNL: 10,
    isBorrowing: false,
    isAaveV3: true,
    isV2: false,
  },
  {
    type: 'LP',
    id: '7',
    chainId: SupportedChainId.mainnet,
    market: 'Aave',
    token: 'usdc',
    name: 'Position 7',
    notional: 1200,
    margin: 240,
    termEndTimestampInMS: 1654022400000,
    status: {
      variant: 'in-range',
      value: 80,
    },
    unrealizedPNL: 30,
    realizedPNL: 60,
    isBorrowing: true,
    isAaveV3: true,
    isV2: false,
  },
  {
    type: 'Fixed',
    id: '8',
    chainId: SupportedChainId.avalanche,
    market: 'Compound',
    token: 'usdt',
    name: 'Position 8',
    notional: 800,
    margin: 160,
    termEndTimestampInMS: 1654022400000,
    status: {
      variant: 'paying',
      value: 70,
    },
    unrealizedPNL: -10,
    realizedPNL: -20,
    isBorrowing: false,
    isAaveV3: false,
    isV2: true,
  },
  {
    type: 'Variable',
    id: '9',
    chainId: SupportedChainId.arbitrum,
    market: 'Lido',
    token: 'usdt',
    name: 'Position 9',
    notional: 1600,
    margin: 320,
    termEndTimestampInMS: 1654022400000,
    status: {
      variant: 'receiving',
      value: 30,
    },
    unrealizedPNL: 25,
    realizedPNL: 50,
    isBorrowing: true,
    isAaveV3: true,
    isV2: true,
  },
  {
    type: 'Fixed',
    id: '10',
    chainId: SupportedChainId.mainnet,
    market: 'Rocket',
    token: 'eth',
    name: 'Position 10',
    notional: 1800,
    margin: 360,
    termEndTimestampInMS: 1654022400000,
    status: {
      variant: 'none',
      value: 0,
    },
    unrealizedPNL: 15,
    realizedPNL: 30,
    isBorrowing: false,
    isAaveV3: false,
    isV2: false,
  },
  {
    type: 'LP',
    id: '11',
    chainId: SupportedChainId.avalanche,
    market: 'GMX:GLP',
    token: 'usdc',
    name: 'Position 11',
    notional: 2200,
    margin: 440,
    termEndTimestampInMS: 1654022400000,
    status: {
      variant: 'in-range',
      value: 90,
    },
    unrealizedPNL: 40,
    realizedPNL: 80,
    isBorrowing: true,
    isAaveV3: true,
    isV2: false,
  },
];
