/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { VAMMStorage, VAMMStorageInterface } from "../VAMMStorage";

const _abi = [
  {
    inputs: [],
    name: "paused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060838061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80635c975abb14602d575b600080fd5b60125460399060ff1681565b604051901515815260200160405180910390f3fea264697066735822122035a238c9b7816c977d2223de1e491178a994b73ab980d19268a84fc3c101d84564736f6c63430008090033";

export class VAMMStorage__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<VAMMStorage> {
    return super.deploy(overrides || {}) as Promise<VAMMStorage>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): VAMMStorage {
    return super.attach(address) as VAMMStorage;
  }
  connect(signer: Signer): VAMMStorage__factory {
    return super.connect(signer) as VAMMStorage__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): VAMMStorageInterface {
    return new utils.Interface(_abi) as VAMMStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): VAMMStorage {
    return new Contract(address, _abi, signerOrProvider) as VAMMStorage;
  }
}
