#!/bin/sh

BRANCH=$(git rev-parse --abbrev-ref HEAD)
REGEX="^(develop|main|staging|((feature|fix|docs|chore|refactor|test)\/.+))$"

if ! [[ $BRANCH =~ $REGEX ]]; then
  echo "Your commit was rejected due to branching name"
  echo "Please rename your branch with $REGEX syntax"
  echo "Required prefix can be one of: feature|fix|docs|chore|refactor|test"
  exit 1
fi

. "$(dirname "$0")/_/husky.sh"

yarn lint-staged
