/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface MarginEngineInterface extends ethers.utils.Interface {
  functions: {
    "MAX_CACHE_MAX_AGE_IN_SECONDS()": FunctionFragment;
    "MAX_LIQUIDATOR_REWARD_WAD()": FunctionFragment;
    "MAX_LOOKBACK_WINDOW_IN_SECONDS()": FunctionFragment;
    "MIN_LOOKBACK_WINDOW_IN_SECONDS()": FunctionFragment;
    "cacheMaxAgeInSeconds()": FunctionFragment;
    "collectProtocol(address,uint256)": FunctionFragment;
    "factory()": FunctionFragment;
    "fcm()": FunctionFragment;
    "getHistoricalApy()": FunctionFragment;
    "getHistoricalApyReadOnly()": FunctionFragment;
    "getPosition(address,int24,int24)": FunctionFragment;
    "getPositionMarginRequirement(address,int24,int24,bool)": FunctionFragment;
    "initialize(address,address,uint256,uint256)": FunctionFragment;
    "liquidatePosition(address,int24,int24)": FunctionFragment;
    "liquidatorRewardWad()": FunctionFragment;
    "lookbackWindowInSeconds()": FunctionFragment;
    "owner()": FunctionFragment;
    "paused()": FunctionFragment;
    "rateOracle()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setCacheMaxAgeInSeconds(uint256)": FunctionFragment;
    "setFCM(address)": FunctionFragment;
    "setLiquidatorReward(uint256)": FunctionFragment;
    "setLookbackWindowInSeconds(uint256)": FunctionFragment;
    "setMarginCalculatorParameters((uint256,uint256,int256,int256,int256,int256,int256,int256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256))": FunctionFragment;
    "setVAMM(address)": FunctionFragment;
    "settlePosition(address,int24,int24)": FunctionFragment;
    "termEndTimestampWad()": FunctionFragment;
    "termStartTimestampWad()": FunctionFragment;
    "transferMarginToFCMTrader(address,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "underlyingToken()": FunctionFragment;
    "updatePositionMargin(address,int24,int24,int256)": FunctionFragment;
    "updatePositionPostVAMMInducedMintBurn((address,int24,int24,int128))": FunctionFragment;
    "updatePositionPostVAMMInducedSwap(address,int24,int24,int256,int256,uint256,int256)": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "vamm()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "MAX_CACHE_MAX_AGE_IN_SECONDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_LIQUIDATOR_REWARD_WAD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_LOOKBACK_WINDOW_IN_SECONDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_LOOKBACK_WINDOW_IN_SECONDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cacheMaxAgeInSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collectProtocol",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(functionFragment: "fcm", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getHistoricalApy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHistoricalApyReadOnly",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPositionMarginRequirement",
    values: [string, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidatePosition",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidatorRewardWad",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lookbackWindowInSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rateOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCacheMaxAgeInSeconds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setFCM", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setLiquidatorReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setLookbackWindowInSeconds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMarginCalculatorParameters",
    values: [
      {
        apyUpperMultiplierWad: BigNumberish;
        apyLowerMultiplierWad: BigNumberish;
        sigmaSquaredWad: BigNumberish;
        alphaWad: BigNumberish;
        betaWad: BigNumberish;
        xiUpperWad: BigNumberish;
        xiLowerWad: BigNumberish;
        tMaxWad: BigNumberish;
        devMulLeftUnwindLMWad: BigNumberish;
        devMulRightUnwindLMWad: BigNumberish;
        devMulLeftUnwindIMWad: BigNumberish;
        devMulRightUnwindIMWad: BigNumberish;
        fixedRateDeviationMinLeftUnwindLMWad: BigNumberish;
        fixedRateDeviationMinRightUnwindLMWad: BigNumberish;
        fixedRateDeviationMinLeftUnwindIMWad: BigNumberish;
        fixedRateDeviationMinRightUnwindIMWad: BigNumberish;
        gammaWad: BigNumberish;
        minMarginToIncentiviseLiquidators: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(functionFragment: "setVAMM", values: [string]): string;
  encodeFunctionData(
    functionFragment: "settlePosition",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "termEndTimestampWad",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "termStartTimestampWad",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferMarginToFCMTrader",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "underlyingToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updatePositionMargin",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePositionPostVAMMInducedMintBurn",
    values: [
      {
        owner: string;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        liquidityDelta: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePositionPostVAMMInducedSwap",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "upgradeTo", values: [string]): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "vamm", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "MAX_CACHE_MAX_AGE_IN_SECONDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_LIQUIDATOR_REWARD_WAD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_LOOKBACK_WINDOW_IN_SECONDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_LOOKBACK_WINDOW_IN_SECONDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cacheMaxAgeInSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fcm", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getHistoricalApy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHistoricalApyReadOnly",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPositionMarginRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidatePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidatorRewardWad",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lookbackWindowInSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rateOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCacheMaxAgeInSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFCM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setLiquidatorReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLookbackWindowInSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMarginCalculatorParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setVAMM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settlePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "termEndTimestampWad",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "termStartTimestampWad",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferMarginToFCMTrader",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "underlyingToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePositionMargin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePositionPostVAMMInducedMintBurn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePositionPostVAMMInducedSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vamm", data: BytesLike): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "CacheMaxAgeSetting(uint256)": EventFragment;
    "FCMSetting(address)": EventFragment;
    "HistoricalApy(uint256)": EventFragment;
    "HistoricalApyWindowSetting(uint256)": EventFragment;
    "LiquidatorRewardSetting(uint256)": EventFragment;
    "MarginCalculatorParametersSetting(tuple)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "PositionLiquidation(address,int24,int24,address,int256,uint256)": EventFragment;
    "PositionMarginUpdate(address,address,int24,int24,int256)": EventFragment;
    "PositionSettlement(address,int24,int24,int256)": EventFragment;
    "PositionUpdate(address,int24,int24,uint128,int256,int256,int256,uint256)": EventFragment;
    "ProtocolCollection(address,address,uint256)": EventFragment;
    "Unpaused(address)": EventFragment;
    "Upgraded(address)": EventFragment;
    "VAMMSetting(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CacheMaxAgeSetting"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FCMSetting"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "HistoricalApy"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "HistoricalApyWindowSetting"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LiquidatorRewardSetting"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "MarginCalculatorParametersSetting"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PositionLiquidation"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PositionMarginUpdate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PositionSettlement"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PositionUpdate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProtocolCollection"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VAMMSetting"): EventFragment;
}

export type AdminChangedEvent = TypedEvent<
  [string, string] & { previousAdmin: string; newAdmin: string }
>;

export type BeaconUpgradedEvent = TypedEvent<[string] & { beacon: string }>;

export type CacheMaxAgeSettingEvent = TypedEvent<
  [BigNumber] & { cacheMaxAgeInSeconds: BigNumber }
>;

export type FCMSettingEvent = TypedEvent<[string] & { fcm: string }>;

export type HistoricalApyEvent = TypedEvent<[BigNumber] & { value: BigNumber }>;

export type HistoricalApyWindowSettingEvent = TypedEvent<
  [BigNumber] & { secondsAgo: BigNumber }
>;

export type LiquidatorRewardSettingEvent = TypedEvent<
  [BigNumber] & { liquidatorRewardWad: BigNumber }
>;

export type MarginCalculatorParametersSettingEvent = TypedEvent<
  [
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      apyUpperMultiplierWad: BigNumber;
      apyLowerMultiplierWad: BigNumber;
      sigmaSquaredWad: BigNumber;
      alphaWad: BigNumber;
      betaWad: BigNumber;
      xiUpperWad: BigNumber;
      xiLowerWad: BigNumber;
      tMaxWad: BigNumber;
      devMulLeftUnwindLMWad: BigNumber;
      devMulRightUnwindLMWad: BigNumber;
      devMulLeftUnwindIMWad: BigNumber;
      devMulRightUnwindIMWad: BigNumber;
      fixedRateDeviationMinLeftUnwindLMWad: BigNumber;
      fixedRateDeviationMinRightUnwindLMWad: BigNumber;
      fixedRateDeviationMinLeftUnwindIMWad: BigNumber;
      fixedRateDeviationMinRightUnwindIMWad: BigNumber;
      gammaWad: BigNumber;
      minMarginToIncentiviseLiquidators: BigNumber;
    }
  ] & {
    marginCalculatorParameters: [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      apyUpperMultiplierWad: BigNumber;
      apyLowerMultiplierWad: BigNumber;
      sigmaSquaredWad: BigNumber;
      alphaWad: BigNumber;
      betaWad: BigNumber;
      xiUpperWad: BigNumber;
      xiLowerWad: BigNumber;
      tMaxWad: BigNumber;
      devMulLeftUnwindLMWad: BigNumber;
      devMulRightUnwindLMWad: BigNumber;
      devMulLeftUnwindIMWad: BigNumber;
      devMulRightUnwindIMWad: BigNumber;
      fixedRateDeviationMinLeftUnwindLMWad: BigNumber;
      fixedRateDeviationMinRightUnwindLMWad: BigNumber;
      fixedRateDeviationMinLeftUnwindIMWad: BigNumber;
      fixedRateDeviationMinRightUnwindIMWad: BigNumber;
      gammaWad: BigNumber;
      minMarginToIncentiviseLiquidators: BigNumber;
    };
  }
>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type PausedEvent = TypedEvent<[string] & { account: string }>;

export type PositionLiquidationEvent = TypedEvent<
  [string, number, number, string, BigNumber, BigNumber] & {
    owner: string;
    tickLower: number;
    tickUpper: number;
    liquidator: string;
    notionalUnwound: BigNumber;
    liquidatorReward: BigNumber;
  }
>;

export type PositionMarginUpdateEvent = TypedEvent<
  [string, string, number, number, BigNumber] & {
    sender: string;
    owner: string;
    tickLower: number;
    tickUpper: number;
    marginDelta: BigNumber;
  }
>;

export type PositionSettlementEvent = TypedEvent<
  [string, number, number, BigNumber] & {
    owner: string;
    tickLower: number;
    tickUpper: number;
    settlementCashflow: BigNumber;
  }
>;

export type PositionUpdateEvent = TypedEvent<
  [
    string,
    number,
    number,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    owner: string;
    tickLower: number;
    tickUpper: number;
    _liquidity: BigNumber;
    margin: BigNumber;
    fixedTokenBalance: BigNumber;
    variableTokenBalance: BigNumber;
    accumulatedFees: BigNumber;
  }
>;

export type ProtocolCollectionEvent = TypedEvent<
  [string, string, BigNumber] & {
    sender: string;
    recipient: string;
    amount: BigNumber;
  }
>;

export type UnpausedEvent = TypedEvent<[string] & { account: string }>;

export type UpgradedEvent = TypedEvent<[string] & { implementation: string }>;

export type VAMMSettingEvent = TypedEvent<[string] & { vamm: string }>;

export class MarginEngine extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MarginEngineInterface;

  functions: {
    MAX_CACHE_MAX_AGE_IN_SECONDS(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    MAX_LIQUIDATOR_REWARD_WAD(overrides?: CallOverrides): Promise<[BigNumber]>;

    MAX_LOOKBACK_WINDOW_IN_SECONDS(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    MIN_LOOKBACK_WINDOW_IN_SECONDS(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    cacheMaxAgeInSeconds(overrides?: CallOverrides): Promise<[BigNumber]>;

    collectProtocol(
      _recipient: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    fcm(overrides?: CallOverrides): Promise<[string]>;

    getHistoricalApy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getHistoricalApyReadOnly(overrides?: CallOverrides): Promise<[BigNumber]>;

    getPosition(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getPositionMarginRequirement(
      _recipient: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      _isLM: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initialize(
      __underlyingToken: string,
      __rateOracle: string,
      __termStartTimestampWad: BigNumberish,
      __termEndTimestampWad: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    liquidatePosition(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    liquidatorRewardWad(overrides?: CallOverrides): Promise<[BigNumber]>;

    lookbackWindowInSeconds(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    rateOracle(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCacheMaxAgeInSeconds(
      _newCacheMaxAgeInSeconds: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFCM(
      _newFCM: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setLiquidatorReward(
      _newLiquidatorRewardWad: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setLookbackWindowInSeconds(
      _newSecondsAgo: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMarginCalculatorParameters(
      _marginCalculatorParameters: {
        apyUpperMultiplierWad: BigNumberish;
        apyLowerMultiplierWad: BigNumberish;
        sigmaSquaredWad: BigNumberish;
        alphaWad: BigNumberish;
        betaWad: BigNumberish;
        xiUpperWad: BigNumberish;
        xiLowerWad: BigNumberish;
        tMaxWad: BigNumberish;
        devMulLeftUnwindLMWad: BigNumberish;
        devMulRightUnwindLMWad: BigNumberish;
        devMulLeftUnwindIMWad: BigNumberish;
        devMulRightUnwindIMWad: BigNumberish;
        fixedRateDeviationMinLeftUnwindLMWad: BigNumberish;
        fixedRateDeviationMinRightUnwindLMWad: BigNumberish;
        fixedRateDeviationMinLeftUnwindIMWad: BigNumberish;
        fixedRateDeviationMinRightUnwindIMWad: BigNumberish;
        gammaWad: BigNumberish;
        minMarginToIncentiviseLiquidators: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setVAMM(
      _vAMM: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    settlePosition(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    termEndTimestampWad(overrides?: CallOverrides): Promise<[BigNumber]>;

    termStartTimestampWad(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferMarginToFCMTrader(
      _account: string,
      _marginDelta: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    underlyingToken(overrides?: CallOverrides): Promise<[string]>;

    updatePositionMargin(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      _marginDelta: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updatePositionPostVAMMInducedMintBurn(
      _params: {
        owner: string;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        liquidityDelta: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updatePositionPostVAMMInducedSwap(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      _fixedTokenDelta: BigNumberish,
      _variableTokenDelta: BigNumberish,
      _cumulativeFeeIncurred: BigNumberish,
      _fixedTokenDeltaUnbalanced: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    vamm(overrides?: CallOverrides): Promise<[string]>;
  };

  MAX_CACHE_MAX_AGE_IN_SECONDS(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_LIQUIDATOR_REWARD_WAD(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_LOOKBACK_WINDOW_IN_SECONDS(overrides?: CallOverrides): Promise<BigNumber>;

  MIN_LOOKBACK_WINDOW_IN_SECONDS(overrides?: CallOverrides): Promise<BigNumber>;

  cacheMaxAgeInSeconds(overrides?: CallOverrides): Promise<BigNumber>;

  collectProtocol(
    _recipient: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  factory(overrides?: CallOverrides): Promise<string>;

  fcm(overrides?: CallOverrides): Promise<string>;

  getHistoricalApy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getHistoricalApyReadOnly(overrides?: CallOverrides): Promise<BigNumber>;

  getPosition(
    _owner: string,
    _tickLower: BigNumberish,
    _tickUpper: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getPositionMarginRequirement(
    _recipient: string,
    _tickLower: BigNumberish,
    _tickUpper: BigNumberish,
    _isLM: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initialize(
    __underlyingToken: string,
    __rateOracle: string,
    __termStartTimestampWad: BigNumberish,
    __termEndTimestampWad: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  liquidatePosition(
    _owner: string,
    _tickLower: BigNumberish,
    _tickUpper: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  liquidatorRewardWad(overrides?: CallOverrides): Promise<BigNumber>;

  lookbackWindowInSeconds(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  rateOracle(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCacheMaxAgeInSeconds(
    _newCacheMaxAgeInSeconds: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFCM(
    _newFCM: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setLiquidatorReward(
    _newLiquidatorRewardWad: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setLookbackWindowInSeconds(
    _newSecondsAgo: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMarginCalculatorParameters(
    _marginCalculatorParameters: {
      apyUpperMultiplierWad: BigNumberish;
      apyLowerMultiplierWad: BigNumberish;
      sigmaSquaredWad: BigNumberish;
      alphaWad: BigNumberish;
      betaWad: BigNumberish;
      xiUpperWad: BigNumberish;
      xiLowerWad: BigNumberish;
      tMaxWad: BigNumberish;
      devMulLeftUnwindLMWad: BigNumberish;
      devMulRightUnwindLMWad: BigNumberish;
      devMulLeftUnwindIMWad: BigNumberish;
      devMulRightUnwindIMWad: BigNumberish;
      fixedRateDeviationMinLeftUnwindLMWad: BigNumberish;
      fixedRateDeviationMinRightUnwindLMWad: BigNumberish;
      fixedRateDeviationMinLeftUnwindIMWad: BigNumberish;
      fixedRateDeviationMinRightUnwindIMWad: BigNumberish;
      gammaWad: BigNumberish;
      minMarginToIncentiviseLiquidators: BigNumberish;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setVAMM(
    _vAMM: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  settlePosition(
    _owner: string,
    _tickLower: BigNumberish,
    _tickUpper: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  termEndTimestampWad(overrides?: CallOverrides): Promise<BigNumber>;

  termStartTimestampWad(overrides?: CallOverrides): Promise<BigNumber>;

  transferMarginToFCMTrader(
    _account: string,
    _marginDelta: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  underlyingToken(overrides?: CallOverrides): Promise<string>;

  updatePositionMargin(
    _owner: string,
    _tickLower: BigNumberish,
    _tickUpper: BigNumberish,
    _marginDelta: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updatePositionPostVAMMInducedMintBurn(
    _params: {
      owner: string;
      tickLower: BigNumberish;
      tickUpper: BigNumberish;
      liquidityDelta: BigNumberish;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updatePositionPostVAMMInducedSwap(
    _owner: string,
    _tickLower: BigNumberish,
    _tickUpper: BigNumberish,
    _fixedTokenDelta: BigNumberish,
    _variableTokenDelta: BigNumberish,
    _cumulativeFeeIncurred: BigNumberish,
    _fixedTokenDeltaUnbalanced: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgradeTo(
    newImplementation: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: string,
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  vamm(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    MAX_CACHE_MAX_AGE_IN_SECONDS(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_LIQUIDATOR_REWARD_WAD(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_LOOKBACK_WINDOW_IN_SECONDS(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    MIN_LOOKBACK_WINDOW_IN_SECONDS(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cacheMaxAgeInSeconds(overrides?: CallOverrides): Promise<BigNumber>;

    collectProtocol(
      _recipient: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    factory(overrides?: CallOverrides): Promise<string>;

    fcm(overrides?: CallOverrides): Promise<string>;

    getHistoricalApy(overrides?: CallOverrides): Promise<BigNumber>;

    getHistoricalApyReadOnly(overrides?: CallOverrides): Promise<BigNumber>;

    getPosition(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        boolean,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        isSettled: boolean;
        _liquidity: BigNumber;
        margin: BigNumber;
        fixedTokenGrowthInsideLastX128: BigNumber;
        variableTokenGrowthInsideLastX128: BigNumber;
        fixedTokenBalance: BigNumber;
        variableTokenBalance: BigNumber;
        feeGrowthInsideLastX128: BigNumber;
        rewardPerAmount: BigNumber;
        accumulatedFees: BigNumber;
      }
    >;

    getPositionMarginRequirement(
      _recipient: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      _isLM: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      __underlyingToken: string,
      __rateOracle: string,
      __termStartTimestampWad: BigNumberish,
      __termEndTimestampWad: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    liquidatePosition(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidatorRewardWad(overrides?: CallOverrides): Promise<BigNumber>;

    lookbackWindowInSeconds(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    rateOracle(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setCacheMaxAgeInSeconds(
      _newCacheMaxAgeInSeconds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setFCM(_newFCM: string, overrides?: CallOverrides): Promise<void>;

    setLiquidatorReward(
      _newLiquidatorRewardWad: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setLookbackWindowInSeconds(
      _newSecondsAgo: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMarginCalculatorParameters(
      _marginCalculatorParameters: {
        apyUpperMultiplierWad: BigNumberish;
        apyLowerMultiplierWad: BigNumberish;
        sigmaSquaredWad: BigNumberish;
        alphaWad: BigNumberish;
        betaWad: BigNumberish;
        xiUpperWad: BigNumberish;
        xiLowerWad: BigNumberish;
        tMaxWad: BigNumberish;
        devMulLeftUnwindLMWad: BigNumberish;
        devMulRightUnwindLMWad: BigNumberish;
        devMulLeftUnwindIMWad: BigNumberish;
        devMulRightUnwindIMWad: BigNumberish;
        fixedRateDeviationMinLeftUnwindLMWad: BigNumberish;
        fixedRateDeviationMinRightUnwindLMWad: BigNumberish;
        fixedRateDeviationMinLeftUnwindIMWad: BigNumberish;
        fixedRateDeviationMinRightUnwindIMWad: BigNumberish;
        gammaWad: BigNumberish;
        minMarginToIncentiviseLiquidators: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    setVAMM(_vAMM: string, overrides?: CallOverrides): Promise<void>;

    settlePosition(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    termEndTimestampWad(overrides?: CallOverrides): Promise<BigNumber>;

    termStartTimestampWad(overrides?: CallOverrides): Promise<BigNumber>;

    transferMarginToFCMTrader(
      _account: string,
      _marginDelta: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    underlyingToken(overrides?: CallOverrides): Promise<string>;

    updatePositionMargin(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      _marginDelta: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updatePositionPostVAMMInducedMintBurn(
      _params: {
        owner: string;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        liquidityDelta: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updatePositionPostVAMMInducedSwap(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      _fixedTokenDelta: BigNumberish,
      _variableTokenDelta: BigNumberish,
      _cumulativeFeeIncurred: BigNumberish,
      _fixedTokenDeltaUnbalanced: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    upgradeTo(
      newImplementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    vamm(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): TypedEventFilter<
      [string, string],
      { previousAdmin: string; newAdmin: string }
    >;

    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): TypedEventFilter<
      [string, string],
      { previousAdmin: string; newAdmin: string }
    >;

    "BeaconUpgraded(address)"(
      beacon?: string | null
    ): TypedEventFilter<[string], { beacon: string }>;

    BeaconUpgraded(
      beacon?: string | null
    ): TypedEventFilter<[string], { beacon: string }>;

    "CacheMaxAgeSetting(uint256)"(
      cacheMaxAgeInSeconds?: null
    ): TypedEventFilter<[BigNumber], { cacheMaxAgeInSeconds: BigNumber }>;

    CacheMaxAgeSetting(
      cacheMaxAgeInSeconds?: null
    ): TypedEventFilter<[BigNumber], { cacheMaxAgeInSeconds: BigNumber }>;

    "FCMSetting(address)"(
      fcm?: string | null
    ): TypedEventFilter<[string], { fcm: string }>;

    FCMSetting(
      fcm?: string | null
    ): TypedEventFilter<[string], { fcm: string }>;

    "HistoricalApy(uint256)"(
      value?: null
    ): TypedEventFilter<[BigNumber], { value: BigNumber }>;

    HistoricalApy(
      value?: null
    ): TypedEventFilter<[BigNumber], { value: BigNumber }>;

    "HistoricalApyWindowSetting(uint256)"(
      secondsAgo?: null
    ): TypedEventFilter<[BigNumber], { secondsAgo: BigNumber }>;

    HistoricalApyWindowSetting(
      secondsAgo?: null
    ): TypedEventFilter<[BigNumber], { secondsAgo: BigNumber }>;

    "LiquidatorRewardSetting(uint256)"(
      liquidatorRewardWad?: null
    ): TypedEventFilter<[BigNumber], { liquidatorRewardWad: BigNumber }>;

    LiquidatorRewardSetting(
      liquidatorRewardWad?: null
    ): TypedEventFilter<[BigNumber], { liquidatorRewardWad: BigNumber }>;

    "MarginCalculatorParametersSetting(tuple)"(
      marginCalculatorParameters?: null
    ): TypedEventFilter<
      [
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          apyUpperMultiplierWad: BigNumber;
          apyLowerMultiplierWad: BigNumber;
          sigmaSquaredWad: BigNumber;
          alphaWad: BigNumber;
          betaWad: BigNumber;
          xiUpperWad: BigNumber;
          xiLowerWad: BigNumber;
          tMaxWad: BigNumber;
          devMulLeftUnwindLMWad: BigNumber;
          devMulRightUnwindLMWad: BigNumber;
          devMulLeftUnwindIMWad: BigNumber;
          devMulRightUnwindIMWad: BigNumber;
          fixedRateDeviationMinLeftUnwindLMWad: BigNumber;
          fixedRateDeviationMinRightUnwindLMWad: BigNumber;
          fixedRateDeviationMinLeftUnwindIMWad: BigNumber;
          fixedRateDeviationMinRightUnwindIMWad: BigNumber;
          gammaWad: BigNumber;
          minMarginToIncentiviseLiquidators: BigNumber;
        }
      ],
      {
        marginCalculatorParameters: [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          apyUpperMultiplierWad: BigNumber;
          apyLowerMultiplierWad: BigNumber;
          sigmaSquaredWad: BigNumber;
          alphaWad: BigNumber;
          betaWad: BigNumber;
          xiUpperWad: BigNumber;
          xiLowerWad: BigNumber;
          tMaxWad: BigNumber;
          devMulLeftUnwindLMWad: BigNumber;
          devMulRightUnwindLMWad: BigNumber;
          devMulLeftUnwindIMWad: BigNumber;
          devMulRightUnwindIMWad: BigNumber;
          fixedRateDeviationMinLeftUnwindLMWad: BigNumber;
          fixedRateDeviationMinRightUnwindLMWad: BigNumber;
          fixedRateDeviationMinLeftUnwindIMWad: BigNumber;
          fixedRateDeviationMinRightUnwindIMWad: BigNumber;
          gammaWad: BigNumber;
          minMarginToIncentiviseLiquidators: BigNumber;
        };
      }
    >;

    MarginCalculatorParametersSetting(
      marginCalculatorParameters?: null
    ): TypedEventFilter<
      [
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          apyUpperMultiplierWad: BigNumber;
          apyLowerMultiplierWad: BigNumber;
          sigmaSquaredWad: BigNumber;
          alphaWad: BigNumber;
          betaWad: BigNumber;
          xiUpperWad: BigNumber;
          xiLowerWad: BigNumber;
          tMaxWad: BigNumber;
          devMulLeftUnwindLMWad: BigNumber;
          devMulRightUnwindLMWad: BigNumber;
          devMulLeftUnwindIMWad: BigNumber;
          devMulRightUnwindIMWad: BigNumber;
          fixedRateDeviationMinLeftUnwindLMWad: BigNumber;
          fixedRateDeviationMinRightUnwindLMWad: BigNumber;
          fixedRateDeviationMinLeftUnwindIMWad: BigNumber;
          fixedRateDeviationMinRightUnwindIMWad: BigNumber;
          gammaWad: BigNumber;
          minMarginToIncentiviseLiquidators: BigNumber;
        }
      ],
      {
        marginCalculatorParameters: [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          apyUpperMultiplierWad: BigNumber;
          apyLowerMultiplierWad: BigNumber;
          sigmaSquaredWad: BigNumber;
          alphaWad: BigNumber;
          betaWad: BigNumber;
          xiUpperWad: BigNumber;
          xiLowerWad: BigNumber;
          tMaxWad: BigNumber;
          devMulLeftUnwindLMWad: BigNumber;
          devMulRightUnwindLMWad: BigNumber;
          devMulLeftUnwindIMWad: BigNumber;
          devMulRightUnwindIMWad: BigNumber;
          fixedRateDeviationMinLeftUnwindLMWad: BigNumber;
          fixedRateDeviationMinRightUnwindLMWad: BigNumber;
          fixedRateDeviationMinLeftUnwindIMWad: BigNumber;
          fixedRateDeviationMinRightUnwindIMWad: BigNumber;
          gammaWad: BigNumber;
          minMarginToIncentiviseLiquidators: BigNumber;
        };
      }
    >;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "Paused(address)"(
      account?: null
    ): TypedEventFilter<[string], { account: string }>;

    Paused(account?: null): TypedEventFilter<[string], { account: string }>;

    "PositionLiquidation(address,int24,int24,address,int256,uint256)"(
      owner?: string | null,
      tickLower?: BigNumberish | null,
      tickUpper?: BigNumberish | null,
      liquidator?: null,
      notionalUnwound?: null,
      liquidatorReward?: null
    ): TypedEventFilter<
      [string, number, number, string, BigNumber, BigNumber],
      {
        owner: string;
        tickLower: number;
        tickUpper: number;
        liquidator: string;
        notionalUnwound: BigNumber;
        liquidatorReward: BigNumber;
      }
    >;

    PositionLiquidation(
      owner?: string | null,
      tickLower?: BigNumberish | null,
      tickUpper?: BigNumberish | null,
      liquidator?: null,
      notionalUnwound?: null,
      liquidatorReward?: null
    ): TypedEventFilter<
      [string, number, number, string, BigNumber, BigNumber],
      {
        owner: string;
        tickLower: number;
        tickUpper: number;
        liquidator: string;
        notionalUnwound: BigNumber;
        liquidatorReward: BigNumber;
      }
    >;

    "PositionMarginUpdate(address,address,int24,int24,int256)"(
      sender?: null,
      owner?: string | null,
      tickLower?: BigNumberish | null,
      tickUpper?: BigNumberish | null,
      marginDelta?: null
    ): TypedEventFilter<
      [string, string, number, number, BigNumber],
      {
        sender: string;
        owner: string;
        tickLower: number;
        tickUpper: number;
        marginDelta: BigNumber;
      }
    >;

    PositionMarginUpdate(
      sender?: null,
      owner?: string | null,
      tickLower?: BigNumberish | null,
      tickUpper?: BigNumberish | null,
      marginDelta?: null
    ): TypedEventFilter<
      [string, string, number, number, BigNumber],
      {
        sender: string;
        owner: string;
        tickLower: number;
        tickUpper: number;
        marginDelta: BigNumber;
      }
    >;

    "PositionSettlement(address,int24,int24,int256)"(
      owner?: string | null,
      tickLower?: BigNumberish | null,
      tickUpper?: BigNumberish | null,
      settlementCashflow?: null
    ): TypedEventFilter<
      [string, number, number, BigNumber],
      {
        owner: string;
        tickLower: number;
        tickUpper: number;
        settlementCashflow: BigNumber;
      }
    >;

    PositionSettlement(
      owner?: string | null,
      tickLower?: BigNumberish | null,
      tickUpper?: BigNumberish | null,
      settlementCashflow?: null
    ): TypedEventFilter<
      [string, number, number, BigNumber],
      {
        owner: string;
        tickLower: number;
        tickUpper: number;
        settlementCashflow: BigNumber;
      }
    >;

    "PositionUpdate(address,int24,int24,uint128,int256,int256,int256,uint256)"(
      owner?: string | null,
      tickLower?: BigNumberish | null,
      tickUpper?: BigNumberish | null,
      _liquidity?: null,
      margin?: null,
      fixedTokenBalance?: null,
      variableTokenBalance?: null,
      accumulatedFees?: null
    ): TypedEventFilter<
      [
        string,
        number,
        number,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ],
      {
        owner: string;
        tickLower: number;
        tickUpper: number;
        _liquidity: BigNumber;
        margin: BigNumber;
        fixedTokenBalance: BigNumber;
        variableTokenBalance: BigNumber;
        accumulatedFees: BigNumber;
      }
    >;

    PositionUpdate(
      owner?: string | null,
      tickLower?: BigNumberish | null,
      tickUpper?: BigNumberish | null,
      _liquidity?: null,
      margin?: null,
      fixedTokenBalance?: null,
      variableTokenBalance?: null,
      accumulatedFees?: null
    ): TypedEventFilter<
      [
        string,
        number,
        number,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ],
      {
        owner: string;
        tickLower: number;
        tickUpper: number;
        _liquidity: BigNumber;
        margin: BigNumber;
        fixedTokenBalance: BigNumber;
        variableTokenBalance: BigNumber;
        accumulatedFees: BigNumber;
      }
    >;

    "ProtocolCollection(address,address,uint256)"(
      sender?: null,
      recipient?: string | null,
      amount?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { sender: string; recipient: string; amount: BigNumber }
    >;

    ProtocolCollection(
      sender?: null,
      recipient?: string | null,
      amount?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { sender: string; recipient: string; amount: BigNumber }
    >;

    "Unpaused(address)"(
      account?: null
    ): TypedEventFilter<[string], { account: string }>;

    Unpaused(account?: null): TypedEventFilter<[string], { account: string }>;

    "Upgraded(address)"(
      implementation?: string | null
    ): TypedEventFilter<[string], { implementation: string }>;

    Upgraded(
      implementation?: string | null
    ): TypedEventFilter<[string], { implementation: string }>;

    "VAMMSetting(address)"(
      vamm?: string | null
    ): TypedEventFilter<[string], { vamm: string }>;

    VAMMSetting(
      vamm?: string | null
    ): TypedEventFilter<[string], { vamm: string }>;
  };

  estimateGas: {
    MAX_CACHE_MAX_AGE_IN_SECONDS(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_LIQUIDATOR_REWARD_WAD(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_LOOKBACK_WINDOW_IN_SECONDS(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    MIN_LOOKBACK_WINDOW_IN_SECONDS(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cacheMaxAgeInSeconds(overrides?: CallOverrides): Promise<BigNumber>;

    collectProtocol(
      _recipient: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    fcm(overrides?: CallOverrides): Promise<BigNumber>;

    getHistoricalApy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getHistoricalApyReadOnly(overrides?: CallOverrides): Promise<BigNumber>;

    getPosition(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getPositionMarginRequirement(
      _recipient: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      _isLM: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initialize(
      __underlyingToken: string,
      __rateOracle: string,
      __termStartTimestampWad: BigNumberish,
      __termEndTimestampWad: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    liquidatePosition(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    liquidatorRewardWad(overrides?: CallOverrides): Promise<BigNumber>;

    lookbackWindowInSeconds(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    rateOracle(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCacheMaxAgeInSeconds(
      _newCacheMaxAgeInSeconds: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFCM(
      _newFCM: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setLiquidatorReward(
      _newLiquidatorRewardWad: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setLookbackWindowInSeconds(
      _newSecondsAgo: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMarginCalculatorParameters(
      _marginCalculatorParameters: {
        apyUpperMultiplierWad: BigNumberish;
        apyLowerMultiplierWad: BigNumberish;
        sigmaSquaredWad: BigNumberish;
        alphaWad: BigNumberish;
        betaWad: BigNumberish;
        xiUpperWad: BigNumberish;
        xiLowerWad: BigNumberish;
        tMaxWad: BigNumberish;
        devMulLeftUnwindLMWad: BigNumberish;
        devMulRightUnwindLMWad: BigNumberish;
        devMulLeftUnwindIMWad: BigNumberish;
        devMulRightUnwindIMWad: BigNumberish;
        fixedRateDeviationMinLeftUnwindLMWad: BigNumberish;
        fixedRateDeviationMinRightUnwindLMWad: BigNumberish;
        fixedRateDeviationMinLeftUnwindIMWad: BigNumberish;
        fixedRateDeviationMinRightUnwindIMWad: BigNumberish;
        gammaWad: BigNumberish;
        minMarginToIncentiviseLiquidators: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setVAMM(
      _vAMM: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    settlePosition(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    termEndTimestampWad(overrides?: CallOverrides): Promise<BigNumber>;

    termStartTimestampWad(overrides?: CallOverrides): Promise<BigNumber>;

    transferMarginToFCMTrader(
      _account: string,
      _marginDelta: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    underlyingToken(overrides?: CallOverrides): Promise<BigNumber>;

    updatePositionMargin(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      _marginDelta: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updatePositionPostVAMMInducedMintBurn(
      _params: {
        owner: string;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        liquidityDelta: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updatePositionPostVAMMInducedSwap(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      _fixedTokenDelta: BigNumberish,
      _variableTokenDelta: BigNumberish,
      _cumulativeFeeIncurred: BigNumberish,
      _fixedTokenDeltaUnbalanced: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    vamm(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX_CACHE_MAX_AGE_IN_SECONDS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MAX_LIQUIDATOR_REWARD_WAD(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MAX_LOOKBACK_WINDOW_IN_SECONDS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MIN_LOOKBACK_WINDOW_IN_SECONDS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cacheMaxAgeInSeconds(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    collectProtocol(
      _recipient: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fcm(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getHistoricalApy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getHistoricalApyReadOnly(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPosition(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getPositionMarginRequirement(
      _recipient: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      _isLM: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      __underlyingToken: string,
      __rateOracle: string,
      __termStartTimestampWad: BigNumberish,
      __termEndTimestampWad: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    liquidatePosition(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    liquidatorRewardWad(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lookbackWindowInSeconds(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rateOracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCacheMaxAgeInSeconds(
      _newCacheMaxAgeInSeconds: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFCM(
      _newFCM: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setLiquidatorReward(
      _newLiquidatorRewardWad: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setLookbackWindowInSeconds(
      _newSecondsAgo: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMarginCalculatorParameters(
      _marginCalculatorParameters: {
        apyUpperMultiplierWad: BigNumberish;
        apyLowerMultiplierWad: BigNumberish;
        sigmaSquaredWad: BigNumberish;
        alphaWad: BigNumberish;
        betaWad: BigNumberish;
        xiUpperWad: BigNumberish;
        xiLowerWad: BigNumberish;
        tMaxWad: BigNumberish;
        devMulLeftUnwindLMWad: BigNumberish;
        devMulRightUnwindLMWad: BigNumberish;
        devMulLeftUnwindIMWad: BigNumberish;
        devMulRightUnwindIMWad: BigNumberish;
        fixedRateDeviationMinLeftUnwindLMWad: BigNumberish;
        fixedRateDeviationMinRightUnwindLMWad: BigNumberish;
        fixedRateDeviationMinLeftUnwindIMWad: BigNumberish;
        fixedRateDeviationMinRightUnwindIMWad: BigNumberish;
        gammaWad: BigNumberish;
        minMarginToIncentiviseLiquidators: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setVAMM(
      _vAMM: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    settlePosition(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    termEndTimestampWad(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    termStartTimestampWad(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferMarginToFCMTrader(
      _account: string,
      _marginDelta: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    underlyingToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updatePositionMargin(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      _marginDelta: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updatePositionPostVAMMInducedMintBurn(
      _params: {
        owner: string;
        tickLower: BigNumberish;
        tickUpper: BigNumberish;
        liquidityDelta: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updatePositionPostVAMMInducedSwap(
      _owner: string,
      _tickLower: BigNumberish,
      _tickUpper: BigNumberish,
      _fixedTokenDelta: BigNumberish,
      _variableTokenDelta: BigNumberish,
      _cumulativeFeeIncurred: BigNumberish,
      _fixedTokenDeltaUnbalanced: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    vamm(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
