/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface MockRocketEthInterface extends ethers.utils.Interface {
  functions: {
    "getEthValue(uint256)": FunctionFragment;
    "getLastUpdatedBlock()": FunctionFragment;
    "setInstantUpdates(bool)": FunctionFragment;
    "setLastUpdatedBlock(uint256)": FunctionFragment;
    "setLastUpdatedBlockManipulation(bool)": FunctionFragment;
    "setRethMultiplierInRay(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getEthValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastUpdatedBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setInstantUpdates",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setLastUpdatedBlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setLastUpdatedBlockManipulation",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setRethMultiplierInRay",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getEthValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastUpdatedBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInstantUpdates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLastUpdatedBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLastUpdatedBlockManipulation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRethMultiplierInRay",
    data: BytesLike
  ): Result;

  events: {};
}

export class MockRocketEth extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MockRocketEthInterface;

  functions: {
    getEthValue(
      rethAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getLastUpdatedBlock(overrides?: CallOverrides): Promise<[BigNumber]>;

    setInstantUpdates(
      instantUpdates: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setLastUpdatedBlock(
      lastUpdatedBlock: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setLastUpdatedBlockManipulation(
      lastUpdatedBlockManipulation: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRethMultiplierInRay(
      rethMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getEthValue(
    rethAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getLastUpdatedBlock(overrides?: CallOverrides): Promise<BigNumber>;

  setInstantUpdates(
    instantUpdates: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setLastUpdatedBlock(
    lastUpdatedBlock: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setLastUpdatedBlockManipulation(
    lastUpdatedBlockManipulation: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRethMultiplierInRay(
    rethMultiplier: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getEthValue(
      rethAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLastUpdatedBlock(overrides?: CallOverrides): Promise<BigNumber>;

    setInstantUpdates(
      instantUpdates: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setLastUpdatedBlock(
      lastUpdatedBlock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setLastUpdatedBlockManipulation(
      lastUpdatedBlockManipulation: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setRethMultiplierInRay(
      rethMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getEthValue(
      rethAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLastUpdatedBlock(overrides?: CallOverrides): Promise<BigNumber>;

    setInstantUpdates(
      instantUpdates: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setLastUpdatedBlock(
      lastUpdatedBlock: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setLastUpdatedBlockManipulation(
      lastUpdatedBlockManipulation: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRethMultiplierInRay(
      rethMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getEthValue(
      rethAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLastUpdatedBlock(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setInstantUpdates(
      instantUpdates: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setLastUpdatedBlock(
      lastUpdatedBlock: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setLastUpdatedBlockManipulation(
      lastUpdatedBlockManipulation: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRethMultiplierInRay(
      rethMultiplier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
